server:
  port: 8090
spring:
  application:
    name: file
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
home:
  picture: D:\Desktop\pictures

database:
  username: root
  password: 1234
  fileName: database-backup.sql
  name: online_examination
  hostIP: 127.0.0.1
  hostPort: 3306
  url: C:\Program Files\MySQL\MySQL Server 5.7\bin